site_name: unusual nemo

repo_url: https://github.com/unusualnemo/unusualnemo.github.io

theme:
  name: material
  #custom_dir: overrides
  font:
    text: Atkinson Hyperlegible
  logo: assets/images/logo.png
  favicon: assets/images/favicon.png
  features:
    - navigation.top
    - search.highlight
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
      primary: indigo
      accent: deep orange

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
      primary: indigo
      accent: deep orange

nav:
  - home: 'index.md'
  - about: 'about.md'
  - 'computer science':
    - 'programming': 'programming.md'
    - 'databases': 'databases.md'

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/unusualnemo
      name: unusualnemo on github